CREATE TABLE `websites_data` (
  `id` int NOT NULL AUTO_INCREMENT,
  `uri` varchar(255) NOT NULL,
  `suitecommerce_tag` varchar(800) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `prodbundle_id` varchar(255) DEFAULT NULL,
  `base_label` varchar(255) DEFAULT NULL,
  `version` varchar(255) DEFAULT NULL,
  `date_label` varchar(255) DEFAULT NULL,
  `build_no` varchar(255) DEFAULT NULL,
  `company_id` varchar(255) DEFAULT NULL,
  `application_ld_json` text,
  `div_id_main` text,
  `div_class_main` text,
  `cookies` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `canonical_url` varchar(255) DEFAULT NULL,
  `title` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `seo_generator` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `got_response_from_pre_render` varchar(255) DEFAULT NULL,
  `governance` varchar(255) DEFAULT NULL,
  `perftiming` varchar(255) DEFAULT NULL,
  `perftiming_sqltime` varchar(255) DEFAULT NULL,
  `search_request_details` varchar(1000) DEFAULT NULL,
  `ssp_app_context` varchar(255) DEFAULT NULL,
  `e_commerce_type` varchar(255) DEFAULT NULL,
  `sub_request_status` varchar(255) DEFAULT NULL,
  `background_requests` text,
  `console_content` text,
  `is_cname_mapped` varchar(255) DEFAULT NULL,
  `cname_test_url` varchar(255) DEFAULT NULL,
  `is_https` varchar(255) DEFAULT NULL,
  `screen_capture` varchar(255) DEFAULT NULL,
  `url_input` varchar(255) DEFAULT NULL,
  `source` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT 'Import',
  `is_robots_page_present` varchar(5) DEFAULT NULL,
  `is_sitemap_link_present_in_robots_page` varchar(5) DEFAULT NULL,
  `sitemap_link` varchar(200) DEFAULT NULL,
  `is_sitemap_link_functional` varchar(5) DEFAULT NULL,
  `date_scraped` date DEFAULT (curdate()),
  `got_response_from_pre_render_time` int DEFAULT NULL,
  `div_id_footer_tag` varchar(100) DEFAULT NULL,
  `no_index_no_follow_tags` varchar(100) DEFAULT NULL,
  `sitemap_origin` varchar(100) DEFAULT NULL,
  `robots_page_content` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `is_google_analytics_loaded` varchar(100) DEFAULT NULL,
  `is_applicatin_ld_json_present` varchar(100) DEFAULT NULL,
  `schema_type` varchar(100) DEFAULT NULL,
  `schema_markup_present` varchar(100) DEFAULT NULL,
  `is_meta_description_present` varchar(100) DEFAULT NULL,
  `got_response_from_pre_render_val_1` int DEFAULT NULL,
  `got_response_from_pre_render_val_2` int DEFAULT NULL,
  `got_response_from_pre_render_val_3` int DEFAULT NULL,
  `got_response_from_pre_render_val_average` int DEFAULT NULL,
  `got_response_from_pre_render_val_alerts` varchar(255) DEFAULT NULL,
  `version_name` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=10794 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
